# netlify.toml

# Configurazione per la fase di build e deploy del tuo progetto Next.js
[build]
  # Questo comando istruisce Next.js a costruire la tua applicazione
  # e poi ad esportarla come un set di file HTML, CSS e JavaScript statici.
  # La parte "next export" è cruciale per deploy statici su Netlify.
  command = "next build && next export"

  # Questa è la directory dove Next.js depositerà i file statici esportati.
  # Netlify pubblicherà il contenuto di questa directory come il tuo sito web.
  publish = "out"

  # Se utilizzi le Netlify Functions (per API routes o logiche serverless),
  # specifica qui la directory dove si trovano i tuoi file funzione.
  # Ad esempio, se le tue funzioni sono in 'netlify/functions':
  # functions = "netlify/functions"

# Regole di reindirizzamento (redirects) per il tuo sito.
# Questa regola è essenziale per le Single Page Applications (SPA)
# costruite con Next.js (quando esportate staticamente),
# perché assicura che qualsiasi richiesta URL venga gestita correttamente dal tuo router client-side.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Se hai bisogno di definire intestazioni HTTP personalizzate per il tuo sito.
# Utile per impostare politiche di sicurezza, CORS, caching, ecc.
# Esempio di intestazioni di sicurezza comuni:
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"
#     X-Content-Type-Options = "nosniff"
#     Referrer-Policy = "strict-origin-when-cross-origin"
#     Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
